### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by bachvtuan** [bitpay/i-made-this#13]
I have setup your project successfully, however I don't understand some thing, please guide me :) 
1.  I register an account on https://blockchain.info. after select a file from my computer, it generate hash code such as "mnvky8Pk9YVNBREki14cdL58DAAqNUNih7". I tried to use my account send 0.0005 BTC to this address but blockchain website inform "Invalid Bitcoin Address".  ![screenshot](https://dl.dropboxusercontent.com/u/15258009/invalid%20code.png)
2. Why is  0.0005 BTC and can I send lower price  ?

Thank you.

**Comment by bachvtuan** [comment]
ok.
I found the aswser for my first question.
By modify code

```
$scope.address = new bitcore.Address(publicKey, bitcore.Networks.testnet).toString();
```

to 

```
$scope.address = new bitcore.Address(publicKey, bitcore.Networks.livenet).toString();
```

**Comment by bitjson** [comment]
Great! Maybe @msalcala11 can answer your second question?

**Comment by bachvtuan** [comment]
Can anyone please help me to answer second my question ?

**Comment by msalcala11** [comment]
@bachvtuan - Yes, you may send less than 0.0005 BTC. Just make sure that whatever amount you send is slightly above the market miner fee at the time so that your transaction makes it into a block. You can specify your preferred amount here: https://github.com/bitpay/i-made-this/blob/master/app.js#L130. 

Or better yet, you could submit a pull request with logic that determines the current market fee dynamically and requests that amount from the user. 

Let me know if that helps!

**Comment by bachvtuan** [comment]
Thank you. I made a search yesterday and I know the minimal fee is 1000 satoshis. https://en.bitcoin.it/wiki/Transaction_fees#Technical_info
